#!/usr/bin/env perl
use strictures 1;
use Getopt::Long::Descriptive;
use Plack::Runner;

sub getopt {
    local @ARGV = @_;
    my ( $opt, $usage ) = describe_options(
        'my-program %o <some-arg>',
        [
            'environment=s', "environment",
            { default => $ENV{PDD_ENVIRONMENT} || "dev" }
        ],
        { getopt_conf => [qw/ pass_through /] },
    );
    return $ENV{PDD_ENVIRONMENT} = $opt->environment;
}
sub main {
    getopt(@ARGV);
    my $runner = Plack::Runner->new;
    $runner->parse_options(@ARGV);
    $runner->run;
}
exit main();
